[package]
name = "vpn-macos"
version = "0.1.0"
edition = "2024"

[dependencies]
vpn-core = { workspace = true }
tokio = { workspace = true, features = ["net", "rt-multi-thread"] }
anyhow = { workspace = true }
log = { workspace = true }