[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
vpn-core = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
fastrace = { workspace = true }