[package]
name = "vpn-core"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { workspace = true }
fastrace = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["sync", "macros"] } # Minimal
